### ISSUE TITLE
SRTM issue at startup

### ISSUE THREAD

**Issue by radarku** [radarku/px4-sitl-docker#1]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/MAVProxy/modules/mavproxy_map/srtm.py", line 103, in loadFileList
    data = open(self.filelist_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/.tilecache/SRTM/filelist_python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/MAVProxy/modules/mavproxy_map/srtm.py", line 173, in createFileListHTTP
    parser.feed(data)
  File "/usr/lib/python3.5/html/parser.py", line 110, in feed
    self.rawdata = self.rawdata + data
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by bteich-bbn** [comment]
Possibly related to https://github.com/ArduPilot/MAVProxy/issues/680 ?
